name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Run Flutter tests
        run: flutter test

      - name: Build APK (Android)
        run: flutter build apk --release

      - name: Build IPA (iOS)
        if: github.event_name == 'push'
        run: |
          flutter build ios --release --no-codesign

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
